import type { editor } from "monaco-editor";

/** Polaris dark — JetBrains New UI / Darcula-inspired, not VS Code Dark+. */
export const POLARIS_DARK_THEME: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "", foreground: "BCBEC4" },
    { token: "comment", foreground: "7A7E85", fontStyle: "italic" },
    { token: "string", foreground: "6AAB73" },
    { token: "string.escape", foreground: "CF8E6D" },
    { token: "number", foreground: "2AACB8" },
    { token: "regexp", foreground: "42C3D4" },
    { token: "keyword", foreground: "CF8E6D" },
    { token: "keyword.control", foreground: "CF8E6D" },
    { token: "operator", foreground: "BCBEC4" },
    { token: "delimiter", foreground: "BCBEC4" },
    { token: "type", foreground: "B3AE60" },
    { token: "type.identifier", foreground: "B3AE60" },
    { token: "class", foreground: "B3AE60" },
    { token: "interface", foreground: "B3AE60" },
    { token: "enum", foreground: "B3AE60" },
    { token: "typeParameter", foreground: "B3AE60" },
    { token: "namespace", foreground: "B3AE60" },
    { token: "function", foreground: "56A8F5" },
    { token: "method", foreground: "56A8F5" },
    { token: "variable", foreground: "BCBEC4" },
    { token: "variable.predefined", foreground: "C77DBB" },
    { token: "variable.parameter", foreground: "BCBEC4" },
    { token: "property", foreground: "C77DBB" },
    { token: "attribute.name", foreground: "BABABA" },
    { token: "attribute.value", foreground: "6AAB73" },
    { token: "tag", foreground: "D5B778" },
    { token: "metatag", foreground: "CF8E6D" },
    { token: "constant", foreground: "C77DBB" },
    { token: "annotation", foreground: "BBB529" },
    { token: "invalid", foreground: "F75464" },
  ],
  colors: {
    "editor.background": "#1E1F22",
    "editor.foreground": "#BCBEC4",
    "editorLineNumber.foreground": "#4E5155",
    "editorLineNumber.activeForeground": "#A1A3A7",
    "editorCursor.foreground": "#FFFFFF",
    "editor.selectionBackground": "#214283",
    "editor.inactiveSelectionBackground": "#21428366",
    "editor.selectionHighlightBackground": "#21428344",
    "editor.wordHighlightBackground": "#3C3F4180",
    "editor.wordHighlightStrongBackground": "#3C3F41A0",
    "editor.findMatchBackground": "#32593D",
    "editor.findMatchHighlightBackground": "#3B5140AA",
    "editor.findRangeHighlightBackground": "#3B514066",
    "editor.hoverHighlightBackground": "#3C3F4166",
    "editor.lineHighlightBackground": "#26282E",
    "editor.lineHighlightBorder": "#00000000",
    "editorIndentGuide.background": "#313438",
    "editorIndentGuide.activeBackground": "#4E5155",
    "editorWhitespace.foreground": "#313438",
    "editorBracketMatch.background": "#3C3F4180",
    "editorBracketMatch.border": "#5A5D63",
    "editorGutter.background": "#1E1F22",
    "editorWidget.background": "#2B2D30",
    "editorWidget.border": "#4E5155",
    "editorWidget.foreground": "#DFDFDF",
    "editorSuggestWidget.background": "#2B2D30",
    "editorSuggestWidget.border": "#4E5155",
    "editorSuggestWidget.foreground": "#DFDFDF",
    "editorSuggestWidget.selectedBackground": "#2E436E",
    "editorSuggestWidget.selectedForeground": "#FFFFFF",
    "editorSuggestWidget.selectedIconForeground": "#FFFFFF",
    "editorSuggestWidget.highlightForeground": "#6A9BF5",
    "editorSuggestWidget.focusHighlightForeground": "#A8C7FA",
    "editorHoverWidget.background": "#2B2D30",
    "editorHoverWidget.border": "#4E5155",
    "editorHoverWidget.foreground": "#DFDFDF",
    "editorError.foreground": "#F75464",
    "editorWarning.foreground": "#C9A227",
    "editorInfo.foreground": "#589DF6",
    "editorOverviewRuler.border": "#00000000",
    "scrollbar.shadow": "#00000000",
    "scrollbarSlider.background": "#4E515566",
    "scrollbarSlider.hoverBackground": "#5A5D6388",
    "scrollbarSlider.activeBackground": "#6C707EAA",
    "minimap.background": "#1E1F22",
    "minimapSlider.background": "#4E515544",
    "minimapSlider.hoverBackground": "#5A5D6366",
    "minimapSlider.activeBackground": "#6C707E88",
    "focusBorder": "#3574F000",
    "input.background": "#1E1F22",
    "input.border": "#4E5155",
    "input.foreground": "#DFDFDF",
    "inputOption.activeBorder": "#3574F0",
    "inputValidation.errorBackground": "#3A2323",
    "inputValidation.errorBorder": "#F75464",
    "dropdown.background": "#2B2D30",
    "dropdown.border": "#4E5155",
    "dropdown.foreground": "#DFDFDF",
    "list.activeSelectionBackground": "#2E436E",
    "list.activeSelectionForeground": "#FFFFFF",
    "list.hoverBackground": "#3C3F41",
    "list.hoverForeground": "#DFDFDF",
    "list.focusBackground": "#2E436E",
    "list.focusForeground": "#FFFFFF",
    "list.highlightForeground": "#6A9BF5",
    "peekView.border": "#3574F0",
    "peekViewEditor.background": "#1E1F22",
    "peekViewResult.background": "#2B2D30",
    "peekViewTitle.background": "#2B2D30",
  },
};

/** Polaris light — IntelliJ Light, high-contrast widgets (readable suggest menu). */
export const POLARIS_LIGHT_THEME: editor.IStandaloneThemeData = {
  base: "vs",
  inherit: true,
  rules: [
    { token: "", foreground: "080808" },
    { token: "comment", foreground: "8C8C8C", fontStyle: "italic" },
    { token: "string", foreground: "067D17" },
    { token: "string.escape", foreground: "0033B3" },
    { token: "number", foreground: "1750EB" },
    { token: "regexp", foreground: "0B8A8F" },
    { token: "keyword", foreground: "0033B3" },
    { token: "keyword.control", foreground: "0033B3" },
    { token: "operator", foreground: "080808" },
    { token: "delimiter", foreground: "080808" },
    { token: "type", foreground: "007E1F" },
    { token: "type.identifier", foreground: "007E1F" },
    { token: "class", foreground: "007E1F" },
    { token: "interface", foreground: "007E1F" },
    { token: "function", foreground: "00627A" },
    { token: "method", foreground: "00627A" },
    { token: "variable", foreground: "080808" },
    { token: "variable.predefined", foreground: "871094" },
    { token: "property", foreground: "871094" },
    { token: "attribute.name", foreground: "174AD4" },
    { token: "attribute.value", foreground: "067D17" },
    { token: "tag", foreground: "0033B3" },
    { token: "metatag", foreground: "0033B3" },
    { token: "constant", foreground: "871094" },
    { token: "annotation", foreground: "9E880D" },
    { token: "invalid", foreground: "F50000" },
  ],
  colors: {
    "editor.background": "#FFFFFF",
    "editor.foreground": "#080808",
    "editorLineNumber.foreground": "#A8ADBA",
    "editorLineNumber.activeForeground": "#5A5D63",
    "editorCursor.foreground": "#000000",
    "editor.selectionBackground": "#A6D2FF",
    "editor.inactiveSelectionBackground": "#A6D2FF88",
    "editor.selectionHighlightBackground": "#A6D2FF55",
    "editor.wordHighlightBackground": "#DFE1E580",
    "editor.wordHighlightStrongBackground": "#DFE1E5A0",
    "editor.findMatchBackground": "#FFE86E",
    "editor.findMatchHighlightBackground": "#FFE86E99",
    "editor.findRangeHighlightBackground": "#FFE86E55",
    "editor.lineHighlightBackground": "#F2F3F5",
    "editor.lineHighlightBorder": "#00000000",
    "editorIndentGuide.background": "#E5E7EB",
    "editorIndentGuide.activeBackground": "#C4C6CC",
    "editorWhitespace.foreground": "#E5E7EB",
    "editorBracketMatch.background": "#DFE1E580",
    "editorBracketMatch.border": "#C4C6CC",
    "editorGutter.background": "#FFFFFF",
    "editorWidget.background": "#FFFFFF",
    "editorWidget.border": "#D3D5DB",
    "editorWidget.foreground": "#2B2D30",
    // Suggest menu — dark text on light selection (fixes white-on-blue)
    "editorSuggestWidget.background": "#FFFFFF",
    "editorSuggestWidget.border": "#D3D5DB",
    "editorSuggestWidget.foreground": "#2B2D30",
    "editorSuggestWidget.selectedBackground": "#D4E2FF",
    "editorSuggestWidget.selectedForeground": "#1E1F22",
    "editorSuggestWidget.selectedIconForeground": "#2B2D30",
    "editorSuggestWidget.highlightForeground": "#2470C0",
    "editorSuggestWidget.focusHighlightForeground": "#0033B3",
    "editorHoverWidget.background": "#FFFFFF",
    "editorHoverWidget.border": "#D3D5DB",
    "editorHoverWidget.foreground": "#2B2D30",
    "editorError.foreground": "#DB3B3B",
    "editorWarning.foreground": "#9A7B0A",
    "editorInfo.foreground": "#2470C0",
    "editorOverviewRuler.border": "#00000000",
    "scrollbar.shadow": "#00000000",
    "scrollbarSlider.background": "#C4C6CC66",
    "scrollbarSlider.hoverBackground": "#A8ADBA88",
    "scrollbarSlider.activeBackground": "#6C707EAA",
    "minimap.background": "#FFFFFF",
    "focusBorder": "#3574F000",
    "input.background": "#FFFFFF",
    "input.border": "#D3D5DB",
    "input.foreground": "#2B2D30",
    "dropdown.background": "#FFFFFF",
    "dropdown.border": "#D3D5DB",
    "dropdown.foreground": "#2B2D30",
    "list.activeSelectionBackground": "#D4E2FF",
    "list.activeSelectionForeground": "#1E1F22",
    "list.hoverBackground": "#DFE1E5",
    "list.hoverForeground": "#2B2D30",
    "list.focusBackground": "#D4E2FF",
    "list.focusForeground": "#1E1F22",
    "list.highlightForeground": "#2470C0",
  },
};

export const POLARIS_THEME_DARK = "polaris-dark";
export const POLARIS_THEME_LIGHT = "polaris-light";

export function registerPolarisThemes(monaco: typeof import("monaco-editor")) {
  monaco.editor.defineTheme(POLARIS_THEME_DARK, POLARIS_DARK_THEME);
  monaco.editor.defineTheme(POLARIS_THEME_LIGHT, POLARIS_LIGHT_THEME);
}
