import type { Metadata } from "next";
import { IBM_Plex_Mono, Inter } from "next/font/google";
import ThemeProvider from "@/components/theme-provider";
import { ClerkProvider, Show, SignInButton, SignUpButton, UserButton } from '@clerk/nextjs'

// @ts-expect-error : issue with them css files
import "./globals.css";
import { dark } from "@clerk/themes";
import { ConvexClientProvider } from "@/components/convex-provider";


const ibmPlexMono = IBM_Plex_Mono({
  variable: "--font-ibm-plex-mono",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{
      theme: dark 
    }}>
      <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${ibmPlexMono.variable} antialiased`}
      >
        <ConvexClientProvider>
         <header className="flex justify-end items-center p-4 gap-4 h-16">
            <Show when="signed-out">
              <SignInButton />
              <SignUpButton>
                <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                  Sign Up
                </button>
              </SignUpButton>
            </Show>
            <Show when="signed-in">
              <UserButton />
            </Show>
          </header>
          <ThemeProvider defaultTheme="dark" attribute="class" enableSystem disableTransitionOnChange>
           {children}
          </ThemeProvider>
        </ConvexClientProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
